name: Android CI/CD:
  push:
    branches:
      - 'master'jobs:
  test:
    name: Run KtLint
    runs-on: android
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11.0.9
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.9
      - name: KtLint
        run: sh ./gradlew ktlintCheck
